<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmotionalTonesSeeder extends Seeder
{
    public function run(): void
    {
        $tones = [
            [
                'tone_code' => 'professional',
                'tone_name' => 'احترافي',
                'tone_name_en' => 'Professional',
                'description' => 'نبرة احترافية رسمية مناسبة للأعمال والمراسلات الرسمية',
                'formality_score' => 9,
                'warmth_score' => 5,
                'enthusiasm_score' => 6,
                'directness_score' => 8,
                'system_instructions' => 'Use professional, formal language. Be clear, precise, and respectful. Avoid slang and casual expressions. Maintain a business-appropriate tone.',
                'keywords_to_use' => json_encode(['we are pleased', 'kindly', 'regarding', 'furthermore', 'consequently', 'professional', 'expertise']),
                'keywords_to_avoid' => json_encode(['hey', 'cool', 'awesome', 'stuff', 'things', 'gonna', 'wanna']),
                'sentence_patterns' => json_encode(['We would like to inform you...', 'Please be advised that...', 'We appreciate your...']),
                'good_examples' => json_encode([
                    'We are pleased to inform you that your request has been approved.',
                    'Please find attached the requested documentation.',
                    'We look forward to your response at your earliest convenience.',
                ]),
                'suitable_for' => json_encode(['business', 'legal', 'corporate', 'finance', 'healthcare']),
                'icon' => '💼',
                'color' => '#2563eb',
                'is_active' => true,
                'priority' => 1,
            ],
            [
                'tone_code' => 'friendly',
                'tone_name' => 'ودي',
                'tone_name_en' => 'Friendly',
                'description' => 'نبرة ودية ودافئة تبني علاقة قوية مع القارئ',
                'formality_score' => 5,
                'warmth_score' => 9,
                'enthusiasm_score' => 7,
                'directness_score' => 7,
                'system_instructions' => 'Use warm, approachable language. Be conversational and engaging. Show genuine interest and care. Use positive expressions.',
                'keywords_to_use' => json_encode(['happy to', 'glad', 'wonderful', 'great', 'love to', 'excited', 'appreciate']),
                'keywords_to_avoid' => json_encode(['must', 'required', 'obligated', 'demand', 'insist']),
                'sentence_patterns' => json_encode(['We\'d love to...', 'It\'s great to...', 'We\'re happy to help...']),
                'good_examples' => json_encode([
                    'We\'d love to help you with that!',
                    'Thanks so much for reaching out!',
                    'We\'re here for you anytime you need us.',
                ]),
                'suitable_for' => json_encode(['customer_service', 'hospitality', 'retail', 'education', 'social_media']),
                'icon' => '😊',
                'color' => '#10b981',
                'is_active' => true,
                'priority' => 2,
            ],
            [
                'tone_code' => 'formal',
                'tone_name' => 'رسمي',
                'tone_name_en' => 'Formal',
                'description' => 'نبرة رسمية جداً للمراسلات الحكومية والقانونية',
                'formality_score' => 10,
                'warmth_score' => 3,
                'enthusiasm_score' => 4,
                'directness_score' => 9,
                'system_instructions' => 'Use highly formal, official language. Follow strict grammatical rules. Be extremely precise and professional. Avoid any casual elements.',
                'keywords_to_use' => json_encode(['hereby', 'pursuant to', 'aforementioned', 'herewith', 'undersigned', 'whereas']),
                'keywords_to_avoid' => json_encode(['basically', 'pretty much', 'kind of', 'sort of', 'really', 'very']),
                'sentence_patterns' => json_encode(['It is hereby declared that...', 'In accordance with...', 'The undersigned hereby...']),
                'suitable_for' => json_encode(['legal', 'government', 'diplomatic', 'academic', 'official_documents']),
                'icon' => '🎩',
                'color' => '#1e293b',
                'is_active' => true,
                'priority' => 3,
            ],
            [
                'tone_code' => 'casual',
                'tone_name' => 'عفوي',
                'tone_name_en' => 'Casual',
                'description' => 'نبرة عفوية ومريحة للمحادثات غير الرسمية',
                'formality_score' => 3,
                'warmth_score' => 7,
                'enthusiasm_score' => 6,
                'directness_score' => 8,
                'system_instructions' => 'Use relaxed, conversational language. Be natural and approachable. Use contractions and simple words. Keep it light and easy.',
                'keywords_to_use' => json_encode(['hey', 'cool', 'awesome', 'great', 'sure', 'no problem', 'sounds good']),
                'keywords_to_avoid' => json_encode(['pursuant', 'hereby', 'aforementioned', 'kindly advise']),
                'sentence_patterns' => json_encode(['Hey there!', 'No worries!', 'Sounds good!', 'Let me know if...']),
                'suitable_for' => json_encode(['social_media', 'blogs', 'personal_communication', 'startups']),
                'icon' => '👋',
                'color' => '#f59e0b',
                'is_active' => true,
                'priority' => 4,
            ],
            [
                'tone_code' => 'technical',
                'tone_name' => 'تقني',
                'tone_name_en' => 'Technical',
                'description' => 'نبرة تقنية دقيقة للمحتوى التقني والعلمي',
                'formality_score' => 8,
                'warmth_score' => 4,
                'enthusiasm_score' => 5,
                'directness_score' => 10,
                'system_instructions' => 'Use precise technical terminology. Be accurate and detailed. Focus on facts and specifications. Avoid ambiguity.',
                'keywords_to_use' => json_encode(['specifically', 'precisely', 'configure', 'implement', 'parameter', 'specification', 'algorithm']),
                'keywords_to_avoid' => json_encode(['maybe', 'probably', 'kind of', 'approximately', 'roughly']),
                'sentence_patterns' => json_encode(['The system implements...', 'To configure...', 'The parameter specifies...']),
                'suitable_for' => json_encode(['technology', 'engineering', 'software', 'science', 'research']),
                'icon' => '⚙️',
                'color' => '#6366f1',
                'is_active' => true,
                'priority' => 5,
            ],
            [
                'tone_code' => 'marketing',
                'tone_name' => 'تسويقي',
                'tone_name_en' => 'Marketing',
                'description' => 'نبرة تسويقية مقنعة وجذابة',
                'formality_score' => 6,
                'warmth_score' => 8,
                'enthusiasm_score' => 9,
                'directness_score' => 7,
                'system_instructions' => 'Use persuasive, engaging language. Highlight benefits and value. Create urgency and excitement. Use power words and calls to action.',
                'keywords_to_use' => json_encode(['exclusive', 'limited', 'amazing', 'transform', 'discover', 'unlock', 'revolutionary', 'proven']),
                'keywords_to_avoid' => json_encode(['cheap', 'cost', 'expensive', 'buy', 'purchase']),
                'sentence_patterns' => json_encode(['Discover how...', 'Transform your...', 'Unlock the power of...', 'Don\'t miss out...']),
                'suitable_for' => json_encode(['advertising', 'sales', 'ecommerce', 'promotions', 'campaigns']),
                'icon' => '🎯',
                'color' => '#ec4899',
                'is_active' => true,
                'priority' => 6,
            ],
            [
                'tone_code' => 'creative',
                'tone_name' => 'إبداعي',
                'tone_name_en' => 'Creative',
                'description' => 'نبرة إبداعية فنية مليئة بالخيال',
                'formality_score' => 4,
                'warmth_score' => 7,
                'enthusiasm_score' => 8,
                'directness_score' => 5,
                'system_instructions' => 'Use imaginative, artistic language. Be expressive and colorful. Use metaphors and vivid descriptions. Think outside the box.',
                'keywords_to_use' => json_encode(['imagine', 'envision', 'craft', 'weave', 'paint', 'inspire', 'magical']),
                'keywords_to_avoid' => json_encode(['standard', 'normal', 'regular', 'typical', 'ordinary']),
                'sentence_patterns' => json_encode(['Imagine a world where...', 'Picture this...', 'Let your imagination...']),
                'suitable_for' => json_encode(['arts', 'design', 'entertainment', 'storytelling', 'branding']),
                'icon' => '🎨',
                'color' => '#8b5cf6',
                'is_active' => true,
                'priority' => 7,
            ],
            [
                'tone_code' => 'empathetic',
                'tone_name' => 'متعاطف',
                'tone_name_en' => 'Empathetic',
                'description' => 'نبرة متعاطفة ومتفهمة تظهر الاهتمام والدعم',
                'formality_score' => 6,
                'warmth_score' => 10,
                'enthusiasm_score' => 6,
                'directness_score' => 6,
                'system_instructions' => 'Show understanding and compassion. Acknowledge feelings. Be supportive and caring. Use gentle, reassuring language.',
                'keywords_to_use' => json_encode(['understand', 'appreciate', 'recognize', 'support', 'care', 'here for you']),
                'keywords_to_avoid' => json_encode(['should have', 'must', 'your fault', 'wrong', 'mistake']),
                'sentence_patterns' => json_encode(['We understand how...', 'We appreciate that...', 'We\'re here to support you...']),
                'suitable_for' => json_encode(['healthcare', 'counseling', 'customer_support', 'social_services']),
                'icon' => '💙',
                'color' => '#06b6d4',
                'is_active' => true,
                'priority' => 8,
            ],
            [
                'tone_code' => 'authoritative',
                'tone_name' => 'موثوق',
                'tone_name_en' => 'Authoritative',
                'description' => 'نبرة موثوقة وخبيرة تبني المصداقية',
                'formality_score' => 8,
                'warmth_score' => 5,
                'enthusiasm_score' => 6,
                'directness_score' => 9,
                'system_instructions' => 'Demonstrate expertise and knowledge. Be confident and credible. Use facts and evidence. Establish authority.',
                'keywords_to_use' => json_encode(['research shows', 'proven', 'expert', 'evidence', 'data', 'studies indicate']),
                'keywords_to_avoid' => json_encode(['I think', 'maybe', 'possibly', 'might', 'could be']),
                'sentence_patterns' => json_encode(['Research demonstrates...', 'Evidence shows...', 'Experts agree that...']),
                'suitable_for' => json_encode(['education', 'research', 'consulting', 'thought_leadership']),
                'icon' => '📚',
                'color' => '#0891b2',
                'is_active' => true,
                'priority' => 9,
            ],
        ];

        foreach ($tones as $tone) {
            DB::table('emotional_tones')->updateOrInsert(
                ['tone_code' => $tone['tone_code']],
                array_merge($tone, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
