<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class UpdatedPricingPlansSeeder extends Seeder
{
    public function run(): void
    {
        $timestamp = Carbon::now();
        
        $plans = [
            [
                'name' => 'Free',
                'slug' => 'free',
                'description' => 'Perfect for trying out our translation service',
                'type' => 'free',
                'price_per_translation' => 0,
                'price_per_1k_chars' => 0,
                'price_per_word' => 0,
                'monthly_price' => 0,
                'yearly_price' => 0,
                'monthly_translation_limit' => 150,
                'daily_translation_limit' => 5,
                'max_chars_per_translation' => 500,
                'has_api_access' => 0,
                'has_bulk_translation' => 0,
                'has_advanced_features' => 0,
                'has_priority_support' => 0,
                'allowed_languages' => json_encode(['en', 'es', 'fr', 'de', 'ar']),
                'features' => json_encode([
                    '5 translations per day',
                    '500 characters per translation',
                    'Basic language support (5 languages)',
                    'Standard translation quality',
                    'No voice translation',
                    'No API access',
                    'Community support',
                ]),
                'is_active' => 1,
                'is_public' => 1,
                'sort_order' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Starter',
                'slug' => 'starter',
                'description' => 'Great for individuals and small projects',
                'type' => 'subscription',
                'price_per_translation' => 0,
                'price_per_1k_chars' => 0,
                'price_per_word' => 0,
                'monthly_price' => 19,
                'yearly_price' => 190,
                'monthly_translation_limit' => 1500,
                'daily_translation_limit' => 50,
                'max_chars_per_translation' => 5000,
                'has_api_access' => 0,
                'has_bulk_translation' => 1,
                'has_advanced_features' => 0,
                'has_priority_support' => 0,
                'allowed_languages' => null,
                'features' => json_encode([
                    '50 translations per day',
                    '1,500 translations per month',
                    '5,000 characters per translation',
                    'All 100+ languages supported',
                    '3 voice translations per day',
                    'Cultural context adaptation',
                    'Translation memory',
                    'Bulk document translation',
                    'Email support',
                    'Translation history (30 days)',
                ]),
                'is_active' => 1,
                'is_public' => 1,
                'sort_order' => 2,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Premium',
                'slug' => 'premium',
                'description' => 'For professionals and growing businesses',
                'type' => 'subscription',
                'price_per_translation' => 0,
                'price_per_1k_chars' => 0,
                'price_per_word' => 0,
                'monthly_price' => 99,
                'yearly_price' => 990,
                'monthly_translation_limit' => 10000,
                'daily_translation_limit' => 350,
                'max_chars_per_translation' => 50000,
                'has_api_access' => 1,
                'has_bulk_translation' => 1,
                'has_advanced_features' => 1,
                'has_priority_support' => 0,
                'allowed_languages' => null,
                'features' => json_encode([
                    '350 translations per day',
                    '10,000 translations per month',
                    '50,000 characters per translation',
                    'All 100+ languages supported',
                    '25 voice translations per day',
                    'API access (10,000 requests/month)',
                    'Advanced cultural adaptation',
                    'Industry-specific terminology',
                    'Tone and formality control',
                    'Translation memory & glossaries',
                    'Bulk document translation',
                    'Priority email support',
                    'Translation history (90 days)',
                    'Basic integrations (Zapier, Slack)',
                    'Quality confidence scores',
                ]),
                'is_active' => 1,
                'is_public' => 1,
                'sort_order' => 3,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Extra Premium',
                'slug' => 'extra-premium',
                'description' => 'Maximum power for demanding users and businesses',
                'type' => 'subscription',
                'price_per_translation' => 0,
                'price_per_1k_chars' => 0,
                'price_per_word' => 0,
                'monthly_price' => 199,
                'yearly_price' => 1990,
                'monthly_translation_limit' => 50000,
                'daily_translation_limit' => 2000,
                'max_chars_per_translation' => 200000,
                'has_api_access' => 1,
                'has_bulk_translation' => 1,
                'has_advanced_features' => 1,
                'has_priority_support' => 1,
                'allowed_languages' => null,
                'features' => json_encode([
                    '2,000 translations per day',
                    '50,000 translations per month',
                    '200,000 characters per translation',
                    'All 100+ languages supported',
                    'Unlimited voice translations',
                    'API access (100,000 requests/month)',
                    'Advanced cultural adaptation',
                    'All industry-specific terminologies',
                    'Advanced tone and formality control',
                    'Custom translation memory & glossaries',
                    'Bulk document translation (unlimited)',
                    'Priority support (24/7 email)',
                    'Translation history (unlimited)',
                    'All integrations included',
                    'Quality confidence scores',
                    'Webhook notifications',
                    'Team collaboration features',
                    'Custom API rate limits',
                    'Advanced analytics dashboard',
                ]),
                'is_active' => 1,
                'is_public' => 1,
                'sort_order' => 4,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Enterprise',
                'slug' => 'enterprise',
                'description' => 'Custom solutions for large organizations',
                'type' => 'custom',
                'price_per_translation' => 0,
                'price_per_1k_chars' => 0,
                'price_per_word' => 0,
                'monthly_price' => null,
                'yearly_price' => null,
                'monthly_translation_limit' => null,
                'daily_translation_limit' => null,
                'max_chars_per_translation' => 1000000,
                'has_api_access' => 1,
                'has_bulk_translation' => 1,
                'has_advanced_features' => 1,
                'has_priority_support' => 1,
                'allowed_languages' => null,
                'features' => json_encode([
                    'Unlimited translations',
                    'Unlimited characters per translation',
                    'All 100+ languages supported',
                    'Unlimited voice translations',
                    'Unlimited API access',
                    'Custom API rate limits',
                    'Dedicated infrastructure',
                    'Advanced cultural adaptation',
                    'All industry-specific terminologies',
                    'Custom terminology databases',
                    'Advanced tone and formality control',
                    'Custom translation memory & glossaries',
                    'Bulk document translation (unlimited)',
                    'Dedicated account manager',
                    'Priority support (24/7 phone & email)',
                    'Translation history (unlimited)',
                    'All integrations included',
                    'Custom integrations available',
                    'Quality confidence scores',
                    'Webhook notifications',
                    'Team collaboration features',
                    'Advanced analytics & reporting',
                    'Custom SLA agreements',
                    'On-premise deployment option',
                    'White-label solutions',
                    'Training & onboarding',
                    'Security & compliance certifications',
                ]),
                'is_active' => 1,
                'is_public' => 1,
                'sort_order' => 5,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Pay as You Go',
                'slug' => 'pay-as-you-go',
                'description' => 'Flexible pricing - only pay for what you use',
                'type' => 'pay_per_use',
                'price_per_translation' => 0.10,
                'price_per_1k_chars' => 2.00,
                'price_per_word' => 0.002,
                'monthly_price' => null,
                'yearly_price' => null,
                'monthly_translation_limit' => null,
                'daily_translation_limit' => null,
                'max_chars_per_translation' => 100000,
                'has_api_access' => 1,
                'has_bulk_translation' => 1,
                'has_advanced_features' => 1,
                'has_priority_support' => 0,
                'allowed_languages' => null,
                'features' => json_encode([
                    'No monthly commitment',
                    'Pay only for what you use',
                    '€0.10 per translation',
                    '€2.00 per 1,000 characters',
                    '€0.002 per word',
                    'All 100+ languages supported',
                    'Voice translation (€0.20 per minute)',
                    'API access included',
                    'Cultural context adaptation',
                    'Translation memory',
                    'Bulk document translation',
                    'Email support',
                    'Translation history (60 days)',
                    'No hidden fees',
                    'Top up as needed',
                ]),
                'is_active' => 1,
                'is_public' => 1,
                'sort_order' => 6,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
        ];

        foreach ($plans as $plan) {
            DB::table('pricing_plans')->insert($plan);
        }

        $this->command->info('Successfully created 6 pricing plans!');
    }
}
