# Funding Options for Cultural Translate Platform

# GitHub Sponsors
# github: [your-github-username]

# Patreon
# patreon: cultural-translate

# Open Collective
# open_collective: cultural-translate

# Ko-fi
# ko_fi: culturaltranslate

# Custom Funding Links
custom: 
  - https://culturaltranslate.com/support
  - https://culturaltranslate.com/enterprise
